### ISSUE TITLE
Bounce Error? 

### ISSUE THREAD

**Issue by hpb0002** [danielkummer/useless-box#1]
Hey, I'm new to Arduinos, so I need a bit of help. When I try to upload the code to my Arduino Uno, I get this error:

"Arduino: 1.8.13 (Windows 10), Board: "Arduino Uno"

useless-box:14:10: fatal error: Bounce2.h: No such file or directory

compilation terminated.

exit status 1

Bounce2.h: No such file or directory"

I'm sure I'm missing something, but any help would be appreciated!

**Comment by barry-ha** [comment]
hpb0002: Was your question answered?
If not, I will guess you need to install the "Bounce2" library.
In the Arduino workbench, use Tools > Manage Libraries. 
Search for Bounce2. Click "Install" and try compiling again.
It resolves the "no such file or directory" message for me. I did get more compile errors but I can't help you there; it's not my project. You might need to get more libraries, for any include that uses angle brackets such as "#include <Servo.h>"
Good luck from a random passerby, Barry

**Comment by alexandrosk0** [comment]
Thanks @barry-ha.
I didn't document the arduino IDE setup, but this project is really nothing extra besides valina arduino code with servos and serial logging.

If there anything I can help, just let me know.

**Comment by barry-ha** [comment]
Hi Alex, I know it's been several years, but can you update README.md to suggest a part for the micro servo and higher torque servo? I want to build my own useless box; I'm good with Arduino but don't know where to start choosing servos. The choices on Amazon are overwhelming.
Many thanks, Barry
